// 🔥 SINGLE SOURCE OF TRUTH

const PAYMENT_GATEWAYS = {
  SELCOM: "SELCOM",
  MPESA: "MPESA",
  AIRTEL: "AIRTEL",
};

const SUPPORTED_PAYMENT_GATEWAYS = Object.values(PAYMENT_GATEWAYS);

module.exports = {
  PAYMENT_GATEWAYS,
  SUPPORTED_PAYMENT_GATEWAYS,
};
