/*
|--------------------------------------------------------------------------
| Role Permission Seeder (FINAL - EXPLICIT MAPPING)
|--------------------------------------------------------------------------
*/

const PERMISSIONS = require('../../utils/permission.constants');

exports.assignPermissionsToRoles = async (db) => {
  try {
    const permissions = await db.permission.findMany();

    // map: name → id
    const map = {};
    permissions.forEach((p) => {
      map[p.name] = p.id;
    });

    const roles = await db.systemAdminRole.findMany();
    const roleMap = {};
    roles.forEach((r) => {
      roleMap[r.name] = r.id;
    });
    const rolePermissions = [];

    /*
    |--------------------------------------------------------------------------
    | SUPER ADMIN (ALL)
    |--------------------------------------------------------------------------
    */
    Object.values(PERMISSIONS).forEach((perm) => {
      rolePermissions.push({
        role: 'SUPER_ADMIN',
        permissionId: map[perm],
        systemAdminRoleId: roleMap['SUPER_ADMIN'],
      });
    });

    /*
    |--------------------------------------------------------------------------
    | SUPPORT ADMIN
    |--------------------------------------------------------------------------
    */
    [
      PERMISSIONS.ANALYTICS_DASHBOARD_READ_SYSTEM,

      PERMISSIONS.COMMUNICATION_ANNOUNCEMENT_CREATE_SYSTEM,
      PERMISSIONS.COMMUNICATION_ANNOUNCEMENT_UPDATE_SYSTEM,
      PERMISSIONS.COMMUNICATION_ANNOUNCEMENT_DELETE_SYSTEM,
      PERMISSIONS.COMMUNICATION_ANNOUNCEMENT_READ_SYSTEM,
      PERMISSIONS.COMMUNICATION_ANNOUNCEMENTBYID_READ_SYSTEM,
      PERMISSIONS.COMMUNICATION_MESSAGEBROADCAST_EXECUTE_SYSTEM,
      PERMISSIONS.COMMUNICATION_MESSAGEBATCH_EXECUTE_SYSTEM,
      PERMISSIONS.COMMUNICATION_MESSAGERETRY_EXECUTE_SYSTEM,
      PERMISSIONS.COMMUNICATION_MESSAGESTATS_READ_SYSTEM,
      PERMISSIONS.COMMUNICATION_TEMPLATE_CREATE_SYSTEM,
      PERMISSIONS.COMMUNICATION_TEMPLATE_UPDATE_SYSTEM,
      PERMISSIONS.COMMUNICATION_TEMPLATE_DELETE_SYSTEM,
      PERMISSIONS.COMMUNICATION_TEMPLATE_READ_SYSTEM,
      PERMISSIONS.COMMUNICATION_TEMPLATEBYID_READ_SYSTEM,

      PERMISSIONS.GOVERNANCE_CUSTOMER_READ_SYSTEM,

      PERMISSIONS.REPORTING_SUPPORTREPORT_READ_SYSTEM,
      PERMISSIONS.REPORTING_SUPPORTSUMMARY_READ_SYSTEM,
      PERMISSIONS.REPORTING_SUPPORTSLA_READ_SYSTEM,
      PERMISSIONS.REPORTING_TICKETSPERBUSINESS_READ_SYSTEM,

      PERMISSIONS.SUPPORT_TICKET_CREATE_SYSTEM,
      PERMISSIONS.SUPPORT_TICKET_READ_SYSTEM,
      PERMISSIONS.SUPPORT_TICKETBYID_READ_SYSTEM,
      PERMISSIONS.SUPPORT_TICKET_UPDATE_SYSTEM,
      PERMISSIONS.SUPPORT_TICKETASSIGN_EXECUTE_SYSTEM,
      PERMISSIONS.SUPPORT_TICKETPRIORITY_UPDATE_SYSTEM,
      PERMISSIONS.SUPPORT_TICKETSTATUS_UPDATE_SYSTEM,
      PERMISSIONS.SUPPORT_NOTE_CREATE_SYSTEM,
      PERMISSIONS.SUPPORT_NOTE_READ_SYSTEM,
      PERMISSIONS.SUPPORT_MESSAGE_CREATE_SYSTEM,
      PERMISSIONS.SUPPORT_MESSAGE_READ_SYSTEM,
      PERMISSIONS.SUPPORT_ATTACHMENT_CREATE_SYSTEM,
      PERMISSIONS.SUPPORT_ATTACHMENT_READ_SYSTEM,
      PERMISSIONS.SUPPORT_ATTACHMENTDOWNLOAD_EXECUTE_SYSTEM,
      PERMISSIONS.SUPPORT_ANALYTIC_READ_SYSTEM,
      PERMISSIONS.SUPPORT_BUSINESSTICKET_READ_SYSTEM,
    ].forEach((perm) => {
      rolePermissions.push({
        role: 'SUPPORT_ADMIN',
        permissionId: map[perm],
        systemAdminRoleId: roleMap['SUPPORT_ADMIN'],
      });
    });

    /*
    |--------------------------------------------------------------------------
    | FINANCE ADMIN
    |--------------------------------------------------------------------------
    */
    [
      PERMISSIONS.ANALYTICS_REVENUE_READ_SYSTEM,
      PERMISSIONS.ANALYTICS_CONVERSIONRATE_READ_SYSTEM,
      PERMISSIONS.ANALYTICS_RENEWALRATE_READ_SYSTEM,

      PERMISSIONS.COMMERCE_LEDGER_READ_SYSTEM,
      PERMISSIONS.COMMERCE_LEDGERBYID_READ_SYSTEM,
      PERMISSIONS.COMMERCE_LEDGERDRILLDOWN_READ_SYSTEM,
      PERMISSIONS.COMMERCE_TRANSACTIONREFUND_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_TRANSACTIONADJUSTMENT_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_INVOICEREGENERATE_EXECUTE_SYSTEM,

      PERMISSIONS.COMMERCE_COUPON_CREATE_SYSTEM,
      PERMISSIONS.COMMERCE_COUPON_READ_SYSTEM,
      PERMISSIONS.COMMERCE_COUPON_UPDATE_SYSTEM,

      PERMISSIONS.COMMERCE_PACKAGE_CREATE_SYSTEM,
      PERMISSIONS.COMMERCE_PACKAGE_UPDATE_SYSTEM,
      PERMISSIONS.COMMERCE_PACKAGECONFIGURATION_UPDATE_SYSTEM,
      PERMISSIONS.COMMERCE_PACKAGEDEACTIVATE_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_PACKAGE_READ_SYSTEM,
      PERMISSIONS.COMMERCE_PACKAGEBYID_READ_SYSTEM,

      PERMISSIONS.COMMERCE_SUBSCRIPTIONPLANCHANGE_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_SUBSCRIPTIONCANCEL_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_SUBSCRIPTIONEXTEND_EXECUTE_SYSTEM,
      PERMISSIONS.COMMERCE_SUBSCRIPTIONGRACE_READ_SYSTEM,
      PERMISSIONS.COMMERCE_SUBSCRIPTIONGRACEEXTEND_EXECUTE_SYSTEM,

      PERMISSIONS.REPORTING_TRANSACTIONREPORT_READ_SYSTEM,
      PERMISSIONS.REPORTING_MONTHLYREVENUE_READ_SYSTEM,
      PERMISSIONS.REPORTING_SETUPFEE_READ_SYSTEM,
      PERMISSIONS.REPORTING_SUBSCRIPTIONREVENUE_READ_SYSTEM,
      PERMISSIONS.REPORTING_REFUNDREPORT_READ_SYSTEM,
      PERMISSIONS.REPORTING_COUPONREPORT_READ_SYSTEM,
      PERMISSIONS.REPORTING_EXPORTCREATE_CREATE_SYSTEM,
      PERMISSIONS.REPORTING_EXPORTHISTORY_READ_SYSTEM,
      PERMISSIONS.REPORTING_EXPORTDOWNLOAD_EXECUTE_SYSTEM,
    ].forEach((perm) => {
      rolePermissions.push({
        role: 'FINANCE_ADMIN',
        permissionId: map[perm],
        systemAdminRoleId: roleMap['FINANCE_ADMIN'],
      });
    });

    /*
    |--------------------------------------------------------------------------
    | SECURITY ADMIN
    |--------------------------------------------------------------------------
    */
    [
      PERMISSIONS.ACCESS_MFA_EXECUTE_SYSTEM,
      PERMISSIONS.ACCESS_AUTH_EXECUTE_SYSTEM,
      PERMISSIONS.ACCESS_SESSION_READ_SYSTEM,
      PERMISSIONS.ACCESS_SESSION_EXECUTE_SYSTEM,

      PERMISSIONS.COMPLIANCE_RETENTIONPOLICY_CREATE_SYSTEM,
      PERMISSIONS.COMPLIANCE_RETENTIONPOLICY_UPDATE_SYSTEM,
      PERMISSIONS.COMPLIANCE_RETENTIONPOLICY_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_RETENTIONPOLICYBYRESOURCE_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_RETENTIONPOLICYTOGGLE_EXECUTE_SYSTEM,
      PERMISSIONS.COMPLIANCE_POLICYVERSION_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_POLICYVERSIONBYID_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_DATAREQUEST_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_DATAREQUESTBYID_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_DATAREQUESTAPPROVE_EXECUTE_SYSTEM,
      PERMISSIONS.COMPLIANCE_DATAREQUESTREJECT_EXECUTE_SYSTEM,
      PERMISSIONS.COMPLIANCE_PURGEJOB_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_PURGEJOBBYID_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_PURGEJOBRETRY_EXECUTE_SYSTEM,
      PERMISSIONS.COMPLIANCE_CONSENTLOG_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_CONSENTLOGBYID_READ_SYSTEM,
      PERMISSIONS.COMPLIANCE_EXPORTDOWNLOAD_EXECUTE_SYSTEM,

      PERMISSIONS.GOVERNANCE_USER_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_USERLOCK_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_USERUNLOCK_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_USERSTATUS_UPDATE_SYSTEM,
      PERMISSIONS.GOVERNANCE_USERFORCELOGOUT_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_USERPASSWORDRESET_EXECUTE_SYSTEM,

      PERMISSIONS.GOVERNANCE_CUSTOMERBLACKLIST_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_CUSTOMERUNBLACKLIST_EXECUTE_SYSTEM,

      PERMISSIONS.GOVERNANCE_AUDITLOG_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_RISK_READ_SYSTEM,

      PERMISSIONS.SECURITY_LOGINACTIVITY_READ_SYSTEM,
      PERMISSIONS.SECURITY_AUDITLOG_READ_SYSTEM,
      PERMISSIONS.SECURITY_AUDITLOGBYID_READ_SYSTEM,
      PERMISSIONS.SECURITY_USERSESSION_READ_SYSTEM,
      PERMISSIONS.SECURITY_USERSESSIONREVOKE_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_USERSESSIONREVOKEALL_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_ADMINSESSION_READ_SYSTEM,
      PERMISSIONS.SECURITY_ADMINSESSIONREVOKE_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_ADMINSESSIONREVOKEALL_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_TOKENREVOKE_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_FLAGUSER_CREATE_SYSTEM,
      PERMISSIONS.SECURITY_FLAGTRANSACTION_CREATE_SYSTEM,
      PERMISSIONS.SECURITY_FLAGRESOLVE_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_FLAG_READ_SYSTEM,
      PERMISSIONS.SECURITY_TRANSACTIONRISK_READ_SYSTEM,
      PERMISSIONS.SECURITY_INTEGRITY_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_FORCELOGOUT_EXECUTE_SYSTEM,
      PERMISSIONS.SECURITY_OVERVIEW_READ_SYSTEM,
      PERMISSIONS.SECURITY_INCIDENT_CREATE_SYSTEM,
      PERMISSIONS.SECURITY_INCIDENT_READ_SYSTEM,
      PERMISSIONS.SECURITY_INCIDENTBYID_READ_SYSTEM,
      PERMISSIONS.SECURITY_INCIDENT_UPDATE_SYSTEM,
    ].forEach((perm) => {
      rolePermissions.push({
        role: 'SECURITY_ADMIN',
        permissionId: map[perm],
        systemAdminRoleId: roleMap['SECURITY_ADMIN'],
      });
    });

    /*
    |--------------------------------------------------------------------------
    | OPERATIONS ADMIN
    |--------------------------------------------------------------------------
    */
    [
      PERMISSIONS.ANALYTICS_GROWTH_READ_SYSTEM,
      PERMISSIONS.ANALYTICS_COHORT_READ_SYSTEM,
      PERMISSIONS.ANALYTICS_USAGE_READ_SYSTEM,
      PERMISSIONS.ANALYTICS_TENANTHEALTH_READ_SYSTEM,

      PERMISSIONS.GOVERNANCE_BUSINESSACTIVATE_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSGRACE_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSSUSPEND_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESS_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSTIMELINE_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSREVENUE_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSSUBSCRIPTIONCHANGE_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSGRACEEXTEND_EXECUTE_SYSTEM,
      PERMISSIONS.GOVERNANCE_BUSINESSPROFILE_READ_SYSTEM,
      PERMISSIONS.GOVERNANCE_SEARCH_READ_SYSTEM,

      PERMISSIONS.OPERATION_SYSTEMHEALTH_READ_SYSTEM,
      PERMISSIONS.OPERATION_DBUSAGE_READ_SYSTEM,
      PERMISSIONS.OPERATION_STORAGEUSAGE_READ_SYSTEM,
      PERMISSIONS.OPERATION_APIMETRICS_READ_SYSTEM,
      PERMISSIONS.OPERATION_JOBLOG_READ_SYSTEM,
      PERMISSIONS.OPERATION_JOBRETRY_EXECUTE_SYSTEM,
      PERMISSIONS.OPERATION_WEBHOOKSTATS_READ_SYSTEM,
      PERMISSIONS.OPERATION_GATEWAYSTATS_READ_SYSTEM,
      PERMISSIONS.OPERATION_OVERVIEW_READ_SYSTEM,
      PERMISSIONS.OPERATION_JOBPERFORMANCE_READ_SYSTEM,
      PERMISSIONS.OPERATION_RECENTJOBS_READ_SYSTEM,
      PERMISSIONS.OPERATION_DEADJOBS_READ_SYSTEM,
    ].forEach((perm) => {
      rolePermissions.push({
        role: 'OPERATIONS_ADMIN',
        permissionId: map[perm],
        systemAdminRoleId: roleMap['OPERATIONS_ADMIN'],
      });
    });

    /*
    |--------------------------------------------------------------------------
    | READ ONLY AUDITOR
    |--------------------------------------------------------------------------
    */
    Object.values(PERMISSIONS)
      .filter((p) => p.endsWith('_READ_SYSTEM'))
      .forEach((perm) => {
        rolePermissions.push({
          role: 'READ_ONLY_AUDITOR',
          permissionId: map[perm],
          systemAdminRoleId: roleMap['READ_ONLY_AUDITOR'],
        });
      });

    /*
    |--------------------------------------------------------------------------
    | CLEAN + INSERT
    |--------------------------------------------------------------------------
    */

    const missing = rolePermissions.filter(
      (r) => !r.permissionId || !r.systemAdminRoleId,
    );

    if (missing.length > 0) {
      console.error('\n❌ Missing permission mappings:\n');
      missing.forEach((m) => {
        console.error(`Role: ${m.role}`);
      });
      throw new Error('Invalid permission mapping');
    }

    const cleanData = rolePermissions;

    await db.rolePermission.createMany({
      data: cleanData,
      skipDuplicates: true,
    });

    console.log(`✅ Role permissions assigned: ${cleanData.length}`);
  } catch (error) {
    console.error('❌ Role permission seeding failed:', error.message);
    throw error;
  }
};
